#!/bin/bash

# === METADATA ===
# NAME: block-ai-pr-attribution
# TYPE: claude-hook
# PLUGIN: claude
# DESCRIPTION: PreToolUse hook to block AI attribution in PR titles and descriptions
# CONFIG: CLAUDE_HOOK_PR_ATTRIBUTION_GUARD=true  Guard against AI attribution in PRs
# ================

CLAUDE_HOOK_PR_ATTRIBUTION_GUARD="${CLAUDE_HOOK_PR_ATTRIBUTION_GUARD:-true}"

# Try config files in order (project overrides global)
if [[ -f "$CLAUDE_PROJECT_DIR/.claude/claude-hooks.conf" ]]; then
    # shellcheck source=/dev/null
    source "$CLAUDE_PROJECT_DIR/.claude/claude-hooks.conf"
elif [[ -f "$HOME/.claude/claude-hooks.conf" ]]; then
    # shellcheck source=/dev/null
    source "$HOME/.claude/claude-hooks.conf"
fi

[[ "$CLAUDE_HOOK_PR_ATTRIBUTION_GUARD" != "true" ]] && exit 0

if ! command -v jq >/dev/null 2>&1; then
    exit 0
fi

stdin_data=$(cat)

tool_name=$(echo "$stdin_data" | jq -r '.tool_name // empty')
[[ "$tool_name" != "Bash" ]] && exit 0

command=$(echo "$stdin_data" | jq -r '.tool_input.command // empty')

# Only check gh pr create/edit commands
if ! echo "$command" | grep -qE 'gh\s+pr\s+(create|edit)'; then
    exit 0
fi

deny() {
    local reason="$1"
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"deny\", \"permissionDecisionReason\": \"$reason\"}}"
    exit 0
}

AI_PATTERNS=(
    "Co-Authored-By:.*Claude"
    "Co-Authored-By:.*GPT"
    "Co-Authored-By:.*AI"
    "Generated by Claude"
    "Generated by GPT"
    "Generated with Claude"
    "Generated with GPT"
    "Written by AI"
    "Written by Claude"
    "Written with Claude"
    "AI-assisted"
    "AI assisted"
    "Claude Code"
    "written with cc"
    "made with cc"
    "built with cc"
    "created with cc"
    "using Claude"
    "using GPT"
    "with the help of AI"
    "with the help of Claude"
    "assisted by Claude"
    "assisted by AI"
    "powered by Claude"
    "powered by AI"
)

for pattern in "${AI_PATTERNS[@]}"; do
    if echo "$command" | grep -qiE "$pattern"; then
        deny "PR contains AI attribution (matched: $pattern). Remove AI attribution from PR title/description."
    fi
done

exit 0
