# plugins/claude/setup.sh — Claude Code setup wizard
# Sourced by dotconfigs entry point. Do not execute directly.

# Internal: save CLAUDE_* config to .env (opt-in model)
_claude_save_config() {
    local env_file="$1"

    # Ensure .env exists with header
    if [[ ! -f "$env_file" ]]; then
        cat > "$env_file" <<'EOF'
# dotconfigs configuration
# Generated by: dotconfigs global-configs claude (wizard)
# Re-run wizard: dotconfigs global-configs claude

EOF
    fi

    # Save only opted-in configs (non-empty values)
    # Deploy target (required)
    wizard_save_env "$env_file" "CLAUDE_DEPLOY_TARGET" "$CLAUDE_DEPLOY_TARGET"

    # Settings.json
    if [[ -n "$CLAUDE_SETTINGS_ENABLED" ]]; then
        wizard_save_env "$env_file" "CLAUDE_SETTINGS_ENABLED" "$CLAUDE_SETTINGS_ENABLED"
    fi

    # CLAUDE.md exclusion settings
    if [[ -n "$CLAUDE_MD_EXCLUDE_GLOBAL" ]]; then
        wizard_save_env "$env_file" "CLAUDE_MD_EXCLUDE_GLOBAL" "$CLAUDE_MD_EXCLUDE_GLOBAL"
    fi
    if [[ -n "$CLAUDE_MD_EXCLUDE_PATTERN" ]]; then
        wizard_save_env "$env_file" "CLAUDE_MD_EXCLUDE_PATTERN" "$CLAUDE_MD_EXCLUDE_PATTERN"
    fi

    # CLAUDE.md sections as space-separated list
    if [[ ${#CLAUDE_MD_SECTIONS_ENABLED[@]} -gt 0 ]]; then
        local sections_str="${CLAUDE_MD_SECTIONS_ENABLED[*]}"
        wizard_save_env "$env_file" "CLAUDE_MD_SECTIONS" "$sections_str"
    fi

    # Hooks as space-separated list
    if [[ ${#CLAUDE_HOOKS_ENABLED[@]} -gt 0 ]]; then
        local hooks_str="${CLAUDE_HOOKS_ENABLED[*]}"
        wizard_save_env "$env_file" "CLAUDE_HOOKS_ENABLED" "$hooks_str"
    fi

    # Skills as space-separated list
    if [[ ${#CLAUDE_SKILLS_ENABLED[@]} -gt 0 ]]; then
        local skills_str="${CLAUDE_SKILLS_ENABLED[*]}"
        wizard_save_env "$env_file" "CLAUDE_SKILLS_ENABLED" "$skills_str"
    fi

    # GSD install
    if [[ -n "$CLAUDE_GSD_INSTALL" ]]; then
        wizard_save_env "$env_file" "CLAUDE_GSD_INSTALL" "$CLAUDE_GSD_INSTALL"
    fi

    # Save dotconfigs version (config schema version)
    wizard_save_env "$env_file" "DOTCONFIGS_VERSION" "2.0"
}

# Internal: migrate old unprefixed keys to CLAUDE_* prefix
# Comments out old keys with migration notice
_claude_migrate_old_keys() {
    local env_file="$1"

    if [[ ! -f "$env_file" ]]; then
        return 0
    fi

    # List of old keys to migrate
    local old_keys=(
        "DEPLOY_TARGET"
        "SETTINGS_ENABLED"
        "CLAUDE_SECTIONS"
        "HOOKS_ENABLED"
        "SKILLS_ENABLED"
        "GSD_INSTALL"
        "GIT_USER_NAME"
        "GIT_USER_EMAIL"
        "ALIASES_ENABLED"
        "ALIAS_DEPLOY_NAME"
    )

    # Comment out each old key if it exists (not already commented)
    for key in "${old_keys[@]}"; do
        if grep -q "^${key}=" "$env_file" 2>/dev/null; then
            # Platform-aware sed: comment out the line and add migration notice
            if [[ "$OSTYPE" == "darwin"* ]]; then
                sed -i '' "s|^${key}=|# migrated to CLAUDE_*\n# ${key}=|" "$env_file"
            else
                sed -i "s|^${key}=|# migrated to CLAUDE_*\n# ${key}=|" "$env_file"
            fi
        fi
    done
}

# Internal: configure Deploy targets category
_claude_configure_deploy_targets() {
    local PLUGIN_DIR="$1"

    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  Category: Deploy targets"
    echo "═══════════════════════════════════════════════════════════"
    echo ""

    # Deploy target path
    local default_target="${CLAUDE_DEPLOY_TARGET:-$HOME/.claude}"
    wizard_prompt "Deploy target directory" "$default_target" CLAUDE_DEPLOY_TARGET
    CLAUDE_DEPLOY_TARGET="${CLAUDE_DEPLOY_TARGET/#\~/$HOME}"  # Expand tilde

    # GSD framework
    echo ""
    echo "The Get Shit Done framework provides project planning agents."
    local gsd_default="n"
    [[ "$CLAUDE_GSD_INSTALL" == "true" ]] && gsd_default="y"
    if wizard_yesno "Install GSD framework?" "$gsd_default"; then
        CLAUDE_GSD_INSTALL="true"
    else
        unset CLAUDE_GSD_INSTALL
    fi
}

# Internal: configure Content category
_claude_configure_content() {
    local PLUGIN_DIR="$1"

    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  Category: Content"
    echo "═══════════════════════════════════════════════════════════"
    echo ""

    # CLAUDE.md sections
    echo "Select which CLAUDE.md sections to include:"
    echo ""

    # Discover available sections from plugin directory
    local available_sections=()
    while IFS= read -r section; do
        available_sections+=("$section")
    done < <(discover_claude_sections "$PLUGIN_DIR")

    if [[ ${#available_sections[@]} -eq 0 ]]; then
        echo "  No CLAUDE.md sections found in templates directory"
    else
        # Toggle each section
        local prev_sections="${CLAUDE_MD_SECTIONS:-}"
        local selected_sections=()

        # Pre-populate selected_sections from previous config
        if [[ -n "$prev_sections" ]]; then
            for section in $prev_sections; do
                selected_sections+=("$section")
            done
        else
            # First run: default to all sections
            selected_sections=("${available_sections[@]}")
        fi

        wizard_config_toggle "Select CLAUDE.md sections:" available_sections selected_sections
        CLAUDE_MD_SECTIONS_ENABLED=("${selected_sections[@]}")
    fi

    # Skills (Commands)
    echo ""
    echo "Select which skills to enable:"
    echo ""

    # Discover available skills from plugin directory
    local available_skills=()
    while IFS= read -r skill; do
        available_skills+=("$skill")
    done < <(discover_skills "$PLUGIN_DIR")

    if [[ ${#available_skills[@]} -eq 0 ]]; then
        echo "  No skills found in commands directory"
    else
        local prev_skills="${CLAUDE_SKILLS_ENABLED:-}"
        local selected_skills=()

        # Pre-populate selected_skills from previous config
        if [[ -n "$prev_skills" ]]; then
            for skill in $prev_skills; do
                selected_skills+=("$skill")
            done
        else
            # First run: default to all skills
            selected_skills=("${available_skills[@]}")
        fi

        wizard_config_toggle "Select skills:" available_skills selected_skills
        CLAUDE_SKILLS_ENABLED=("${selected_skills[@]}")
    fi
}

# Internal: configure Behaviour category
_claude_configure_behaviour() {
    local PLUGIN_DIR="$1"

    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  Category: Behaviour"
    echo "═══════════════════════════════════════════════════════════"
    echo ""

    # Settings.json
    echo "Claude Code permission rules control which files Claude can read and which"
    echo "commands it can run. This includes denying access to secrets (*.pem, credentials)"
    echo "and auto-formatting Python files with Ruff."
    echo ""
    local settings_default="n"
    [[ "$CLAUDE_SETTINGS_ENABLED" == "true" ]] && settings_default="y"
    if wizard_yesno "Deploy settings.json to $CLAUDE_DEPLOY_TARGET? (symlinks from dotconfigs repo)" "$settings_default"; then
        CLAUDE_SETTINGS_ENABLED="true"
    else
        unset CLAUDE_SETTINGS_ENABLED
    fi

    # CLAUDE.md Exclusion
    echo ""
    echo "CLAUDE.md files contain project instructions for Claude Code."
    echo "You can exclude them from git repositories to prevent committing"
    echo "project instructions to source control."
    echo ""

    local exclude_default="n"
    [[ "$CLAUDE_MD_EXCLUDE_GLOBAL" == "true" ]] && exclude_default="y"

    if wizard_yesno "Exclude CLAUDE.md from git globally?" "$exclude_default"; then
        CLAUDE_MD_EXCLUDE_GLOBAL="true"

        echo ""
        echo "Select exclusion pattern:"
        echo "  1) CLAUDE.md (root only)"
        echo "  2) **/*CLAUDE.md (all directories)"
        echo ""

        local pattern_default="${CLAUDE_MD_EXCLUDE_PATTERN:-CLAUDE.md}"
        read -p "Choice [1-2, default: ${pattern_default}]: " pattern_choice

        case "$pattern_choice" in
            2)
                CLAUDE_MD_EXCLUDE_PATTERN="**/*CLAUDE.md"
                ;;
            *)
                CLAUDE_MD_EXCLUDE_PATTERN="CLAUDE.md"
                ;;
        esac

        echo "  → Will exclude: $CLAUDE_MD_EXCLUDE_PATTERN"
    else
        unset CLAUDE_MD_EXCLUDE_GLOBAL
        unset CLAUDE_MD_EXCLUDE_PATTERN
    fi

    # Claude Code Hooks
    echo ""
    echo "Select which Claude Code hooks to enable:"
    echo ""

    # Discover available hooks from plugin directory
    local available_hooks=()
    while IFS= read -r hook; do
        available_hooks+=("$hook")
    done < <(discover_hooks "$PLUGIN_DIR")

    if [[ ${#available_hooks[@]} -eq 0 ]]; then
        echo "  No hooks found in hooks directory"
    else
        local prev_hooks="${CLAUDE_HOOKS_ENABLED:-}"
        local selected_hooks=()

        # Pre-populate selected_hooks from previous config
        if [[ -n "$prev_hooks" ]]; then
            for hook in $prev_hooks; do
                selected_hooks+=("$hook")
            done
        else
            # First run: default to all hooks
            selected_hooks=("${available_hooks[@]}")
        fi

        wizard_config_toggle "Select Claude Code hooks:" available_hooks selected_hooks
        CLAUDE_HOOKS_ENABLED=("${selected_hooks[@]}")
    fi
}

# Internal: show configuration summary
_claude_show_summary() {
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  Configuration Summary"
    echo "═══════════════════════════════════════════════════════════"
    echo ""

    # Deploy target (always managed)
    echo "Deploy target:      $CLAUDE_DEPLOY_TARGET"

    # GSD install
    if [[ -n "$CLAUDE_GSD_INSTALL" ]]; then
        echo "GSD install:        $CLAUDE_GSD_INSTALL"
    else
        printf "GSD install:        "
        colour_not_managed
        echo ""
    fi

    # Settings.json
    if [[ -n "$CLAUDE_SETTINGS_ENABLED" ]]; then
        echo "Settings.json:      $CLAUDE_SETTINGS_ENABLED"
    else
        printf "Settings.json:      "
        colour_not_managed
        echo ""
    fi

    # CLAUDE.md exclusion
    if [[ -n "$CLAUDE_MD_EXCLUDE_GLOBAL" ]]; then
        echo "CLAUDE.md exclusion: $CLAUDE_MD_EXCLUDE_GLOBAL ($CLAUDE_MD_EXCLUDE_PATTERN)"
    else
        printf "CLAUDE.md exclusion: "
        colour_not_managed
        echo ""
    fi

    # CLAUDE.md sections
    if [[ ${#CLAUDE_MD_SECTIONS_ENABLED[@]} -gt 0 ]]; then
        echo "CLAUDE.md sections: ${CLAUDE_MD_SECTIONS_ENABLED[*]}"
    else
        printf "CLAUDE.md sections: "
        colour_not_managed
        echo ""
    fi

    # Hooks
    if [[ ${#CLAUDE_HOOKS_ENABLED[@]} -gt 0 ]]; then
        echo "Hooks enabled:      ${CLAUDE_HOOKS_ENABLED[*]}"
    else
        printf "Hooks enabled:      "
        colour_not_managed
        echo ""
    fi

    # Skills
    if [[ ${#CLAUDE_SKILLS_ENABLED[@]} -gt 0 ]]; then
        echo "Skills enabled:     ${CLAUDE_SKILLS_ENABLED[*]}"
    else
        printf "Skills enabled:     "
        colour_not_managed
        echo ""
    fi

    echo ""
}

# Internal: edit mode — show current config and allow editing specific items
_claude_edit_mode() {
    local PLUGIN_DIR="$1"

    while true; do
        echo ""
        echo "═══════════════════════════════════════════════════════════"
        echo "  Current Configuration"
        echo "═══════════════════════════════════════════════════════════"
        echo ""

        # Build display arrays
        local labels=()
        local values=()
        local managed=()

        # 1. Deploy target path
        labels+=("Deploy target path")
        values+=("$CLAUDE_DEPLOY_TARGET")
        managed+=("true")

        # 2. GSD framework install
        labels+=("GSD framework install")
        if [[ -n "$CLAUDE_GSD_INSTALL" ]]; then
            values+=("$CLAUDE_GSD_INSTALL")
            managed+=("true")
        else
            values+=("")
            managed+=("false")
        fi

        # 3. Settings.json enabled
        labels+=("Settings.json enabled")
        if [[ -n "$CLAUDE_SETTINGS_ENABLED" ]]; then
            values+=("$CLAUDE_SETTINGS_ENABLED")
            managed+=("true")
        else
            values+=("")
            managed+=("false")
        fi

        # 4. CLAUDE.md exclusion
        labels+=("CLAUDE.md exclusion")
        if [[ -n "$CLAUDE_MD_EXCLUDE_GLOBAL" ]]; then
            values+=("$CLAUDE_MD_EXCLUDE_GLOBAL ($CLAUDE_MD_EXCLUDE_PATTERN)")
            managed+=("true")
        else
            values+=("")
            managed+=("false")
        fi

        # 5. CLAUDE.md sections
        labels+=("CLAUDE.md sections")
        if [[ ${#CLAUDE_MD_SECTIONS_ENABLED[@]} -gt 0 ]]; then
            values+=("${CLAUDE_MD_SECTIONS_ENABLED[*]}")
            managed+=("true")
        else
            values+=("")
            managed+=("false")
        fi

        # 6. Hooks enabled
        labels+=("Hooks enabled")
        if [[ ${#CLAUDE_HOOKS_ENABLED[@]} -gt 0 ]]; then
            values+=("${CLAUDE_HOOKS_ENABLED[*]}")
            managed+=("true")
        else
            values+=("")
            managed+=("false")
        fi

        # 7. Skills enabled
        labels+=("Skills enabled")
        if [[ ${#CLAUDE_SKILLS_ENABLED[@]} -gt 0 ]]; then
            values+=("${CLAUDE_SKILLS_ENABLED[*]}")
            managed+=("true")
        else
            values+=("")
            managed+=("false")
        fi

        # Display current state
        wizard_edit_mode_display labels values managed

        echo ""
        read -p "Enter numbers to edit (e.g. 3,6), 'categories' to use category menu, or 'done': " edit_choice

        if [[ "$edit_choice" == "done" ]] || [[ -z "$edit_choice" ]]; then
            return 0
        elif [[ "$edit_choice" == "categories" ]]; then
            return 1  # Signal to use category menu
        fi

        # Parse selection
        local max_index=$((${#labels[@]} - 1))
        local selected_indices
        selected_indices=$(wizard_parse_edit_selection "$edit_choice" "$max_index")

        if [[ -z "$selected_indices" ]]; then
            echo "No valid selections. Try again."
            continue
        fi

        # Edit each selected item
        for idx in $selected_indices; do
            case $idx in
                0)
                    # Deploy target path
                    echo ""
                    local default_target="${CLAUDE_DEPLOY_TARGET:-$HOME/.claude}"
                    wizard_prompt "Deploy target directory" "$default_target" CLAUDE_DEPLOY_TARGET
                    CLAUDE_DEPLOY_TARGET="${CLAUDE_DEPLOY_TARGET/#\~/$HOME}"
                    ;;
                1)
                    # GSD framework install
                    echo ""
                    local gsd_default="n"
                    [[ "$CLAUDE_GSD_INSTALL" == "true" ]] && gsd_default="y"
                    if wizard_yesno "Install GSD framework?" "$gsd_default"; then
                        CLAUDE_GSD_INSTALL="true"
                    else
                        unset CLAUDE_GSD_INSTALL
                    fi
                    ;;
                2)
                    # Settings.json enabled
                    echo ""
                    local settings_default="n"
                    [[ "$CLAUDE_SETTINGS_ENABLED" == "true" ]] && settings_default="y"
                    if wizard_yesno "Deploy settings.json?" "$settings_default"; then
                        CLAUDE_SETTINGS_ENABLED="true"
                    else
                        unset CLAUDE_SETTINGS_ENABLED
                    fi
                    ;;
                3)
                    # CLAUDE.md exclusion
                    echo ""
                    local exclude_default="n"
                    [[ "$CLAUDE_MD_EXCLUDE_GLOBAL" == "true" ]] && exclude_default="y"
                    if wizard_yesno "Exclude CLAUDE.md from git globally?" "$exclude_default"; then
                        CLAUDE_MD_EXCLUDE_GLOBAL="true"
                        echo ""
                        echo "Select exclusion pattern:"
                        echo "  1) CLAUDE.md (root only)"
                        echo "  2) **/*CLAUDE.md (all directories)"
                        echo ""
                        local pattern_default="${CLAUDE_MD_EXCLUDE_PATTERN:-CLAUDE.md}"
                        read -p "Choice [1-2, default: ${pattern_default}]: " pattern_choice
                        case "$pattern_choice" in
                            2) CLAUDE_MD_EXCLUDE_PATTERN="**/*CLAUDE.md" ;;
                            *) CLAUDE_MD_EXCLUDE_PATTERN="CLAUDE.md" ;;
                        esac
                    else
                        unset CLAUDE_MD_EXCLUDE_GLOBAL
                        unset CLAUDE_MD_EXCLUDE_PATTERN
                    fi
                    ;;
                4)
                    # CLAUDE.md sections
                    echo ""
                    local available_sections=()
                    while IFS= read -r section; do
                        available_sections+=("$section")
                    done < <(discover_claude_sections "$PLUGIN_DIR")

                    if [[ ${#available_sections[@]} -gt 0 ]]; then
                        local selected_sections=()
                        if [[ ${#CLAUDE_MD_SECTIONS_ENABLED[@]} -gt 0 ]]; then
                            selected_sections=("${CLAUDE_MD_SECTIONS_ENABLED[@]}")
                        fi
                        wizard_config_toggle "Select CLAUDE.md sections:" available_sections selected_sections
                        CLAUDE_MD_SECTIONS_ENABLED=("${selected_sections[@]}")
                    fi
                    ;;
                5)
                    # Hooks enabled
                    echo ""
                    local available_hooks=()
                    while IFS= read -r hook; do
                        available_hooks+=("$hook")
                    done < <(discover_hooks "$PLUGIN_DIR")

                    if [[ ${#available_hooks[@]} -gt 0 ]]; then
                        local selected_hooks=()
                        if [[ ${#CLAUDE_HOOKS_ENABLED[@]} -gt 0 ]]; then
                            selected_hooks=("${CLAUDE_HOOKS_ENABLED[@]}")
                        fi
                        wizard_config_toggle "Select Claude Code hooks:" available_hooks selected_hooks
                        CLAUDE_HOOKS_ENABLED=("${selected_hooks[@]}")
                    fi
                    ;;
                6)
                    # Skills enabled
                    echo ""
                    local available_skills=()
                    while IFS= read -r skill; do
                        available_skills+=("$skill")
                    done < <(discover_skills "$PLUGIN_DIR")

                    if [[ ${#available_skills[@]} -gt 0 ]]; then
                        local selected_skills=()
                        if [[ ${#CLAUDE_SKILLS_ENABLED[@]} -gt 0 ]]; then
                            selected_skills=("${CLAUDE_SKILLS_ENABLED[@]}")
                        fi
                        wizard_config_toggle "Select skills:" available_skills selected_skills
                        CLAUDE_SKILLS_ENABLED=("${selected_skills[@]}")
                    fi
                    ;;
            esac
        done
    done
}

# Main entry point — called by dotconfigs CLI
plugin_claude_setup() {
    # Derive plugin directory from script location
    local PLUGIN_DIR
    PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Determine .env location (repo root)
    local REPO_ROOT
    REPO_ROOT="$(cd "$PLUGIN_DIR/../.." && pwd)"
    local ENV_FILE="$REPO_ROOT/.env"

    # Load existing .env for pre-fill defaults
    if [[ -f "$ENV_FILE" ]]; then
        source "$ENV_FILE"
    fi

    # Initialize colours
    init_colours

    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║              dotconfigs — Claude Configuration             ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""

    # Detect edit mode vs first run
    local edit_mode=false
    if [[ -n "$CLAUDE_DEPLOY_TARGET" ]]; then
        edit_mode=true
    fi

    if $edit_mode; then
        # Edit mode: show current config and allow item-by-item editing
        if _claude_edit_mode "$PLUGIN_DIR"; then
            # User selected 'done', show summary and save
            _claude_show_summary
        else
            # User selected 'categories', fall through to category menu
            edit_mode=false
        fi
    fi

    if ! $edit_mode; then
        # First run or user chose category menu: category-based opt-in flow
        local categories=("Deploy targets" "Content" "Behaviour" "Configure all" "Done — show summary")

        while true; do
            echo ""
            echo "Select a category to configure:"
            echo ""
            local i=1
            for cat in "${categories[@]}"; do
                echo "  $i) $cat"
                i=$((i + 1))
            done
            echo ""

            read -p "Choice [1-${#categories[@]}]: " cat_choice

            case "$cat_choice" in
                1)
                    _claude_configure_deploy_targets "$PLUGIN_DIR"
                    ;;
                2)
                    _claude_configure_content "$PLUGIN_DIR"
                    ;;
                3)
                    _claude_configure_behaviour "$PLUGIN_DIR"
                    ;;
                4)
                    # Configure all
                    _claude_configure_deploy_targets "$PLUGIN_DIR"
                    _claude_configure_content "$PLUGIN_DIR"
                    _claude_configure_behaviour "$PLUGIN_DIR"
                    ;;
                5|"")
                    # Done — show summary
                    break
                    ;;
                *)
                    echo "Invalid choice, try again"
                    ;;
            esac
        done

        _claude_show_summary
    fi

    # Confirm before saving
    echo ""
    if ! wizard_yesno "Save this configuration?" "y"; then
        echo ""
        echo "Configuration not saved. Re-run wizard to try again."
        return 0
    fi

    # Save configuration to .env
    _claude_save_config "$ENV_FILE"

    # Migrate old unprefixed keys
    _claude_migrate_old_keys "$ENV_FILE"

    echo ""
    echo "Configuration saved to $ENV_FILE"
    echo ""
    echo "Next steps:"
    echo "  1. Run 'dots deploy claude' to deploy to filesystem"
    echo "  2. Customise settings in .env if needed"
    echo ""
}
