# plugins/claude/setup.sh — Claude Code setup wizard
# Sourced by dotconfigs entry point. Do not execute directly.

# Internal: save CLAUDE_* config to .env
_claude_save_config() {
    local env_file="$1"

    # Ensure .env exists with header
    if [[ ! -f "$env_file" ]]; then
        cat > "$env_file" <<'EOF'
# dotconfigs configuration
# Generated by: dotconfigs setup claude (wizard)
# Re-run wizard: dotconfigs setup claude

EOF
    fi

    # Save all CLAUDE_* prefixed keys
    wizard_save_env "$env_file" "CLAUDE_DEPLOY_TARGET" "$CLAUDE_DEPLOY_TARGET"
    wizard_save_env "$env_file" "CLAUDE_SETTINGS_ENABLED" "$CLAUDE_SETTINGS_ENABLED"

    # Save CLAUDE.md sections as space-separated list
    local sections_str="${CLAUDE_MD_SECTIONS_ENABLED[*]}"
    wizard_save_env "$env_file" "CLAUDE_MD_SECTIONS" "$sections_str"

    # Save hooks as space-separated list
    local hooks_str="${CLAUDE_HOOKS_ENABLED[*]}"
    wizard_save_env "$env_file" "CLAUDE_HOOKS_ENABLED" "$hooks_str"

    # Save skills as space-separated list
    local skills_str="${CLAUDE_SKILLS_ENABLED[*]}"
    wizard_save_env "$env_file" "CLAUDE_SKILLS_ENABLED" "$skills_str"

    wizard_save_env "$env_file" "CLAUDE_GSD_INSTALL" "$CLAUDE_GSD_INSTALL"
    wizard_save_env "$env_file" "CLAUDE_GIT_USER_NAME" "$CLAUDE_GIT_USER_NAME"
    wizard_save_env "$env_file" "CLAUDE_GIT_USER_EMAIL" "$CLAUDE_GIT_USER_EMAIL"

    # Save dotconfigs version (config schema version)
    wizard_save_env "$env_file" "DOTCONFIGS_VERSION" "2.0"
}

# Internal: migrate old unprefixed keys to CLAUDE_* prefix
# Comments out old keys with migration notice
_claude_migrate_old_keys() {
    local env_file="$1"

    if [[ ! -f "$env_file" ]]; then
        return 0
    fi

    # List of old keys to migrate
    local old_keys=(
        "DEPLOY_TARGET"
        "SETTINGS_ENABLED"
        "CLAUDE_SECTIONS"
        "HOOKS_ENABLED"
        "SKILLS_ENABLED"
        "GSD_INSTALL"
        "GIT_USER_NAME"
        "GIT_USER_EMAIL"
        "ALIASES_ENABLED"
        "ALIAS_DEPLOY_NAME"
    )

    # Comment out each old key if it exists (not already commented)
    for key in "${old_keys[@]}"; do
        if grep -q "^${key}=" "$env_file" 2>/dev/null; then
            # Platform-aware sed: comment out the line and add migration notice
            if [[ "$OSTYPE" == "darwin"* ]]; then
                sed -i '' "s|^${key}=|# migrated to CLAUDE_*\n# ${key}=|" "$env_file"
            else
                sed -i "s|^${key}=|# migrated to CLAUDE_*\n# ${key}=|" "$env_file"
            fi
        fi
    done
}

# Main entry point — called by dotconfigs CLI
plugin_claude_setup() {
    # Derive plugin directory from script location
    local PLUGIN_DIR
    PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Determine .env location (repo root)
    local REPO_ROOT
    REPO_ROOT="$(cd "$PLUGIN_DIR/../.." && pwd)"
    local ENV_FILE="$REPO_ROOT/.env"

    # Load existing .env for pre-fill defaults
    if [[ -f "$ENV_FILE" ]]; then
        source "$ENV_FILE"
    fi

    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║              dotconfigs — Claude Configuration             ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""

    # Step 1: Deploy Target
    wizard_header 1 "Deploy Target"
    echo "Where should Claude configuration be deployed?"
    local default_target="${CLAUDE_DEPLOY_TARGET:-${DEPLOY_TARGET:-$HOME/.claude}}"
    wizard_prompt "Deploy target directory" "$default_target" CLAUDE_DEPLOY_TARGET
    CLAUDE_DEPLOY_TARGET="${CLAUDE_DEPLOY_TARGET/#\~/$HOME}"  # Expand tilde

    # Step 2: Settings.json
    wizard_header 2 "Settings"
    echo "Claude Code permission rules control which files Claude can read and which"
    echo "commands it can run. This includes denying access to secrets (*.pem, credentials)"
    echo "and auto-formatting Python files with Ruff."
    echo ""
    local settings_default="y"
    local prev_settings="${CLAUDE_SETTINGS_ENABLED:-${SETTINGS_ENABLED:-}}"
    [[ "$prev_settings" == "false" ]] && settings_default="n"
    if wizard_yesno "Deploy settings.json to $CLAUDE_DEPLOY_TARGET? (symlinks from dotconfigs repo)" "$settings_default"; then
        CLAUDE_SETTINGS_ENABLED="true"
    else
        CLAUDE_SETTINGS_ENABLED="false"
    fi

    # Step 3: CLAUDE.md sections
    wizard_header 3 "CLAUDE.md Sections"
    echo "Select which sections to include in your global CLAUDE.md"
    echo ""

    # Discover available sections from plugin directory
    local available_sections=()
    while IFS= read -r section; do
        available_sections+=("$section")
    done < <(discover_claude_sections "$PLUGIN_DIR")

    # Toggle each section (pre-fill from previous config)
    local prev_sections="${CLAUDE_MD_SECTIONS:-${CLAUDE_SECTIONS:-}}"
    CLAUDE_MD_SECTIONS_ENABLED=()
    for section in "${available_sections[@]}"; do
        local section_default="y"
        # If we have previous config, only default 'y' for previously enabled sections
        if [[ -n "$prev_sections" ]]; then
            if ! _is_in_list "$section" "$prev_sections"; then
                section_default="n"
            fi
        fi
        if wizard_yesno "  Include ${section}?" "$section_default"; then
            CLAUDE_MD_SECTIONS_ENABLED+=("$section")
        fi
    done

    # Step 4: Claude Code Hooks
    wizard_header 4 "Claude Code Hooks"
    echo "Select which Claude Code hooks to enable"
    echo ""

    # Discover available hooks from plugin directory
    local available_hooks=()
    while IFS= read -r hook; do
        available_hooks+=("$hook")
    done < <(discover_hooks "$PLUGIN_DIR")

    local prev_hooks="${CLAUDE_HOOKS_ENABLED:-${HOOKS_ENABLED:-}}"
    CLAUDE_HOOKS_ENABLED=()
    if [[ ${#available_hooks[@]} -gt 0 ]]; then
        for hook in "${available_hooks[@]}"; do
            local hook_default="y"
            if [[ -n "$prev_hooks" ]]; then
                if ! _is_in_list "$hook" "$prev_hooks"; then
                    hook_default="n"
                fi
            fi
            if wizard_yesno "  Enable ${hook}?" "$hook_default"; then
                CLAUDE_HOOKS_ENABLED+=("$hook")
            fi
        done
    else
        echo "  No hooks found in hooks/ directory"
    fi

    # Step 5: Skills (Commands)
    wizard_header 5 "Skills"
    echo "Select which skills to enable"
    echo ""

    # Discover available skills from plugin directory
    local available_skills=()
    while IFS= read -r skill; do
        available_skills+=("$skill")
    done < <(discover_skills "$PLUGIN_DIR")

    local prev_skills="${CLAUDE_SKILLS_ENABLED:-${SKILLS_ENABLED:-}}"
    CLAUDE_SKILLS_ENABLED=()
    if [[ ${#available_skills[@]} -gt 0 ]]; then
        for skill in "${available_skills[@]}"; do
            local skill_default="y"
            if [[ -n "$prev_skills" ]]; then
                if ! _is_in_list "$skill" "$prev_skills"; then
                    skill_default="n"
                fi
            fi
            if wizard_yesno "  Enable ${skill}?" "$skill_default"; then
                CLAUDE_SKILLS_ENABLED+=("$skill")
            fi
        done
    else
        echo "  No skills found in commands/ directory"
    fi

    # Step 6: GSD Framework
    wizard_header 6 "GSD Framework"
    echo "The Get Shit Done framework provides project planning agents."
    local gsd_default="n"
    local prev_gsd="${CLAUDE_GSD_INSTALL:-${GSD_INSTALL:-}}"
    [[ "$prev_gsd" == "true" ]] && gsd_default="y"
    if wizard_yesno "Install GSD framework?" "$gsd_default"; then
        CLAUDE_GSD_INSTALL="true"
    else
        CLAUDE_GSD_INSTALL="false"
    fi

    # Step 7: Git Identity
    wizard_header 7 "Git Identity"
    echo "Configure global git user.name and user.email"
    echo "(Leave empty to keep existing configuration)"
    echo ""
    local prev_name="${CLAUDE_GIT_USER_NAME:-${GIT_USER_NAME:-}}"
    local prev_email="${CLAUDE_GIT_USER_EMAIL:-${GIT_USER_EMAIL:-}}"
    if [[ -n "$prev_name" ]]; then
        read -p "Git user.name [$prev_name]: " CLAUDE_GIT_USER_NAME
        CLAUDE_GIT_USER_NAME="${CLAUDE_GIT_USER_NAME:-$prev_name}"
    else
        read -p "Git user.name: " CLAUDE_GIT_USER_NAME
    fi
    if [[ -n "$prev_email" ]]; then
        read -p "Git user.email [$prev_email]: " CLAUDE_GIT_USER_EMAIL
        CLAUDE_GIT_USER_EMAIL="${CLAUDE_GIT_USER_EMAIL:-$prev_email}"
    else
        read -p "Git user.email: " CLAUDE_GIT_USER_EMAIL
    fi

    # Summary
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  Configuration Summary"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "Deploy target:      $CLAUDE_DEPLOY_TARGET"
    echo "Settings.json:      $CLAUDE_SETTINGS_ENABLED"
    echo "CLAUDE.md sections: ${CLAUDE_MD_SECTIONS_ENABLED[*]:-none}"
    echo "Hooks enabled:      ${CLAUDE_HOOKS_ENABLED[*]:-none}"
    echo "Skills enabled:     ${CLAUDE_SKILLS_ENABLED[*]:-none}"
    echo "GSD install:        $CLAUDE_GSD_INSTALL"
    if [[ -n "$CLAUDE_GIT_USER_NAME" ]] || [[ -n "$CLAUDE_GIT_USER_EMAIL" ]]; then
        echo "Git identity:       ${CLAUDE_GIT_USER_NAME} <${CLAUDE_GIT_USER_EMAIL}>"
    else
        echo "Git identity:       (unchanged)"
    fi
    echo ""

    # Confirm before saving
    if ! wizard_yesno "Save this configuration?" "y"; then
        echo ""
        echo "Configuration not saved. Re-run wizard to try again."
        return 0
    fi

    # Save configuration to .env
    _claude_save_config "$ENV_FILE"

    # Migrate old unprefixed keys
    _claude_migrate_old_keys "$ENV_FILE"

    echo ""
    echo "Configuration saved to $ENV_FILE"
    echo ""
    echo "Next steps:"
    echo "  1. Run 'dotconfigs deploy claude' to deploy to filesystem"
    echo "  2. Customise settings in .env if needed"
    echo ""
}
